accum_grad: 1
cmvn_file: exp/unified_transformer/global_cmvn
collate_conf:
  feature_dither: 0.0
  feature_extraction_conf:
    feature_type: fbank
    frame_length: 25
    frame_shift: 10
    mel_bins: 80
    using_pitch: false
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 50
    max_w: 80
    num_f_mask: 2
    num_t_mask: 2
    warp_for_time: false
  speed_perturb: true
  wav_distortion_conf:
    distortion_methods: []
    wav_distortion_rate: 0.0
    wav_dither: 0.1
dataset_conf:
  batch_size: 26
  batch_type: static
  max_length: 40960
  min_length: 0
  sort: true
decoder: transformer
decoder_conf:
  attention_heads: 4
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 6
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.0
  src_attention_dropout_rate: 0.0
encoder: transformer
encoder_conf:
  attention_dropout_rate: 0.0
  attention_heads: 4
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  normalize_before: true
  num_blocks: 12
  output_size: 256
  positional_dropout_rate: 0.1
  use_dynamic_chunk: true
grad_clip: 5
input_dim: 80
is_json_cmvn: true
log_interval: 100
max_epoch: 360
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
optim: adam
optim_conf:
  lr: 0.001
output_dim: 4233
raw_wav: true
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
